-- CREATE TABLE students(
-- id integer,
-- first_name text,
-- middle_name text,
-- last_name text,
-- age integer,
-- location text);

-- INSERT INTO students (id,
-- first_name,
-- middle_name,
-- last_name,
-- age,
-- location) 
-- VALUES 
-- (1, 'Juan', 'Blank', 'Cruz', 18, 'Manila'),
-- (2, 'Anne', 'Blank', 'Wall', 20, 'Manila'),
-- (3, 'Theresa', 'Blank', 'Joseph', 21, 'Manila'),
-- (4, 'Issac', 'Blank', 'Gray', 19, 'Laguna'),
-- (5, 'Zack', 'Blank', 'Matthews', 22, 'Marikina'),
-- (6, 'Finn', 'Blank', 'Lam', 25, 'Manila');

